export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "IoT"
  | "OpenAI API"
  | "Machine Learning"
  | "Beautiful Soup"
  | "Scrapy"
  | "Pandas"
  | "Data Analysis"
  | "Web Scraping"
  | "REST APIs"
  | "Material Design"
  | "Provider Pattern"
  | "Responsive Design"
  | "Leadership"
  | "Event Management"
  | "AI"
  | "Robotics"
  | "Project Management"
  | "Data Structures"
  | "Algorithms"
  | "Database Systems"
  | "Computer Vision"
  | "Image Processing"
  | "Software Engineering"
  | "Mathematics"
  | "Analytical Thinking"
  | "Problem Solving"
  | "Academic Excellence"
  | "Postman"
  | "Prisma"
  | "Bootstrap 5"
  | "Mongoose"
  | "Clerk"
  | "Stripe"
  | "OpenAI Assistants API"
  | "Cursor"
  | "Lovable"
  | "V0"
  | "Bolt"
  | "ElevenLabs"
  | "Coqui XTTS"
  | "n8n"
  | "Vapi"
  | "Twillio"
  | "Supabase"
  | "Voiceflow"
  | "GSX2JSON"
  | "Real-time Chat"
  | "Audio Processing"
  | "Location Services"
  | "Excel Integration"
  | "Google APIs"
  | "JSON"
  | "Push Notifications"
  | "Local Storage"
  | "Weather APIs"
  | "Academic Management"
  | "jQuery"
  | "HTML5"
  | "CSS3";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "IoT"
  | "AI/ML"
  | "Data Analysis"
  | "Automation"
  | "Real-time"
  | "Audio" 
  | "APIs"
  | "Academic";

export type ValidExpType = "Personal Project" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "career"
  | "contact"
  | "achievements"
  | "resume";
